### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dmittrey** [dmittrey/csa-lab3#2]
- [x] See harris book(extension for RISC-V)
- [x] Research RISC-V ISA
- [x] Explore tasks and write ISA specification
- [x] Write register specification
- [x] Make process model via drawio
- [x] Research lecture with explaining task
- [x] Implement processor module
- [x] Add simulation
- [x] Debug machine code
- [x] #4
- [x] #3
- [x] #5
- [x] #6
